cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    dbaldwin:
      email: dbaldwin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Test Uno
      password: $2b$12$JAh3W6yyx9C14gNrle8F6.b6IiGCNq2QEyU5GiJd02BQZpJQl5lge
    gabboshow:
      email: gabbo.spina@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Gabriele
      password: $2b$12$3OSdNN4bXKAcYjXMORhzb.qcDfueZWNCcnJkUkzP.twFOJAPGQ8..
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Test Due
      password: $2b$12$NYkkEdNQ98P9Y215boG91.g4BZ1cRk74VoqEbKgmeSeaXyN/r9VKe
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$uNaTgvGPG9rMbzOJHYaPQePw0DUfp1qHBrSq6l4O304qani6pKFpm
    rcouper:
      email: rcouper@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ross Couper
      password: $2b$12$Tir/PbHVmmnt5kgNxgOwMuxNIb2fv2pJ.q71TW8ekvbugCqkye4yu
pre-authorized:
  emails:
  - melsby@gmail.com
